### ISSUE TITLE
Deploy Sage Storybook

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#36]
## What

Deploy the Sage Storybook to either [Chromatic](https://www.chromatic.com/), GitHub Pages, or s3. Chromatic is a free cloud host from the Storybook maintainers. 

We can start with Chromatic, GitHub Pages, or s3 and then maybe look at using Skynet or a decentralized host like Fleek.

We can likely deploy only the Sage version of our Storybook (instead both Rage and Sage) at a certain point, although we may want to keep both so that we have somewhat of a _staging_ and _prod_ type setup for our component library.

## TODOs

- [x] Determine deploy target 
- [x] Add deploy command to root `package.json` in the Sage monorepo
- [ ] Add deploy workflow to GitHub Actions

## Deliverables

Storybook build commands added to the root's `package.json` and a hosted Storybook instance with CI/CD based on the `haus-components` package.

## Resources

- https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/

**Comment by scottrepreneur** [comment]
Check out the deploy workflow being used by the RG system.
https://github.com/raid-guild/design-system/blob/main/.github/workflows/publish.yml

**Comment by jonathanprozzi** [comment]
Making progress on this -- had to make a few adjustments for our workflow and also had to think through a few things with regards to our monorepo @earth2travis

**Comment by jonathanprozzi** [comment]
We'll be working on this on Weds.

**Comment by jonathanprozzi** [comment]
This is resolved by #379

**Comment by earth2travis** [comment]
Blocked by https://github.com/HausDAO/daohaus-monorepo/issues/398

**Comment by earth2travis** [comment]
@jonathanprozzi looks like https://github.com/HausDAO/daohaus-monorepo/issues/398 is ready for review
