### ISSUE TITLE
@daohaus/data: Set up Sage Library

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#39]
## Overview

Create data library in the sage mono repo.

### Todo

- [ ] generate package w/ name: @daohaus/data
- [ ] polyfill for fetch
- [x] see keating's fix for nested dependencies
- [ ] see spec/rage repo for folder structure and initial classes

### resources
https://hackmd.io/wtDwRLeVTsepeDjeiQ0lyg?view

**Comment by jonathanprozzi** [comment]
@skuhlmann looks like that PR merged this in! I wonder why it didn't automatically move into Done.

Is there anything else with this or can we close it out?

**Comment by jonathanprozzi** [comment]
@skuhlmann I think we can move this into Done!
