### ISSUE TITLE
Add Daohaus Connect to Summoner in Navigation

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#62]
# TODO

- [x] Explore adding navigation components to daohaus-connect
- [x] Export connect button on it's own
- [x] Adds context and package to the app
- [x] Navigation should be super simple now - takes props for logo/name/route

## Considerations
- Review Hub app shell/components
- Advanced nav/search ect... are not included in alpha

**Comment by jordanlesich** [comment]
DH Connect is already in Summoner, The different components of DH connect can be imported separately. We just those exploration steps around the switcher element. 

Personally, I think it would be really helpful for it to have it live inside the nav. It could be something like this: 

- If we add a list of apps to nav to as props, then DAOhaus nav will render the switcher
- If we do not pass that list, it won't render. 
- We can also leave a UI slot there so that we could pass in a custom element to render in that space.

**Comment by jonathanprozzi** [comment]
Ah! Good note -- thanks @jordanlesich 
I missed this

**Comment by jordanlesich** [comment]
Marking this as finished as we already integrated this in the Summon-app. 

We explored adding building the switcher drop-down and adding it into the nav for both the SK + JP meeting + the dev meeting. 

I'd say we're set to spec and build this out once the designs are solidified.

**Comment by jordanlesich** [comment]
Adding it to review instead in case there's something I'm missing here.
