### ISSUE TITLE
Git Workflow Doc Page

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#78]
## What

This is related to #32 but is its own page, so it should be its own ticket.

## TODOs

- [x] Establish our git processes as v3 Blacksmiths
- [x] Document current iteration of git processes in the Wiki
- [x] Link to appropriate / relevant docs pages

## Deliverables

- Git Workflow docs page  in the Wiki linked in **Process**

**Comment by jonathanprozzi** [comment]
@earth2travis Wiki link: https://github.com/HausDAO/daohaus-monorepo/wiki/Git-Workflow

**Comment by earth2travis** [comment]
Is this worthing linking in? https://github.com/HausDAO/daohaus-monorepo/wiki/GitHub

**Comment by earth2travis** [comment]
Added link to this page in the Workflow heading on https://github.com/HausDAO/daohaus-monorepo/wiki/GitHub
